export const cities = [
  'Medellín',
  'Bogotá',
  'Cali',
  'Barranquilla',
  'Cartagena',
  'Bucaramanga',
  'Pereira',
  'Manizales',
  'Santa Marta',
  'Cúcuta',
  'Ibagué',
  'Pasto',
  'Neiva',
  'Villavicencio',
  'Armenia',
  'Tunja',
  'Popayán',
  'Sincelejo',
  'Montería',
  'Valledupar',
  'Florencia',
  'Quibdó',
  'Leticia',
  'Puerto Carreño',
  'San Andrés',
  'Mocoa',
  'Yopal',
  'Arauca',
  'Cúcuta',
  'Riohacha',
  'San José del Guaviare',
  'Mitú',
  'Inírida',
  'Puerto Inírida',
  'Tumaco',
  'Buenaventura',
  'Barrancabermeja',
  'Sogamoso',
  'Palmira',
  'Soledad',
];
